NAME			=	Animal
SRC 			= 	main.cpp ./src/Animal.cpp ./src/Cat.cpp ./src/Dog.cpp \
					./src/WrongAnimal.cpp ./src/WrongCat.cpp ./src/Brain.cpp
OBJS 			= 	$(SRC:.cpp=.o)

CC				=	c++
RM				=	rm -f
CFLAGS			=	-Wall -Wextra -Werror -std=c++98

$(NAME):		$(OBJS)
				$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

all:			
				$(CC) $(CFLAGS) -o $(NAME) $(SRC) $(MAIN)

clean:			
				$(RM) $(OBJS)

fclean:			clean
				$(RM) $(NAME)

re:				fclean $(NAME)

.PHONY:			all clean fclean re
